# Generated by release workflow — do not edit manually
class Obs < Formula
  desc "Open-source observability stack CLI (SigNoz + PostHog)"
  homepage "https://github.com/Osillation/obs"
  license "MIT"
  version "0.1.4"

  on_macos do
    on_arm do
      url "https://github.com/Osillation/obs/releases/download/v0.1.4/obs_darwin_arm64.tar.gz"
      sha256 "8f200af413a7b7e40b7ae5e4522fb6402af219e004d19e116575efc41bf91dc7"
    end
    on_intel do
      url "https://github.com/Osillation/obs/releases/download/v0.1.4/obs_darwin_amd64.tar.gz"
      sha256 "95e6743e9680d0abc1d310b083daa14d2819e505b7a3dbddb268af2f5d9860a2"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Osillation/obs/releases/download/v0.1.4/obs_linux_arm64.tar.gz"
      sha256 "4d9721b3c69522cdc7dfed4fabc606365eb5839ce98258936ca8ed7e923da630"
    end
    on_intel do
      url "https://github.com/Osillation/obs/releases/download/v0.1.4/obs_linux_amd64.tar.gz"
      sha256 "9d1e15701ddc292fdd15d5f544247174bc6bb56b2d9ebc79e60c67d07adaec1b"
    end
  end

  def install
    bin.install "obs"
  end

  test do
    system "\#{bin}/obs", "version"
  end
end
